import Wrapper from "@/components/shared/Wrapper/Wrapper";
import "./globals.css";
import type { Metadata } from "next";
import { Sora } from "next/font/google";
import Navbar from "@/components/view/Navbar/Navbar";
import Footer from "@/components/view/Footer";
import Copyright from "@/components/view/Copyright";
import Providers from "@/components/shared/Provider";
import GoToTop from "@/components/shared/GoToTop";

const inter = Sora({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Dine Market",
  description: "Generated by Dine Market",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const theme = {
    colors: {
      heading: "rgb(24 24 29)",
      text: "rgb(24 24 29)",
      white: "#fff",
      black: " #212529",
      helper: "#8490ff",
      bg: "rgb(249 249 255)",
      footer_bg: "#0a1435",
      btn: "rgb(98 84 243)",
      border: "rgba(98, 84, 243, 0.5)",
      hr: "#ffffff",
      gradient:
        "linear-gradient(0deg, rgb(132 144 255) 0%, rgb(98 189 252) 100%)",
      shadow:
        "rgba(0, 0, 0, 0.02) 0px 1px 3px 0px,rgba(27, 31, 35, 0.15) 0px 0px 0px 1px;",
      shadowSupport: " rgba(0, 0, 0, 0.16) 0px 1px 4px",
    },
    media: { mobile: "768px", tab: "998px" },
  };
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
            <Navbar />
          <Wrapper>
            {children}
            <GoToTop/>
            <Footer />
          </Wrapper>
          <Copyright />
        </Providers>
      </body>
    </html>
  );
}
