export { default as hero } from "./hero.webp";
export { default as fetured1 } from "./Featured1.webp";
export { default as fetured2 } from "./Featured2.webp";
export { default as fetured3 } from "./Featured3.webp";
export { default as fetured4 } from "./Featured4.webp";
export { default as event1 } from "./event1.webp";
export { default as event2 } from "./event2.webp";
export { default as event3 } from "./event3.webp";
export { default as feature } from "./feature.webp";
